# Generated by Django 4.2.25 on 2025-11-13 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voluntario',
            old_name='id',
            new_name='id_voluntario',
        ),
    ]
